### ISSUE TITLE
Search Regex Error

### ISSUE THREAD

**Issue by takarakushi** [johngodley/search-regex#78] opened 2021-01-25 06:43 UTC
```
Plugin: 2.4
WordPress: 5.5.3 (single)
PHP: 7.3.14 512M 14400s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
JavaScript: https://test.financial-field.com/wp/wp-content/plugins/search-regex/search-regex.js
REST API: https://test.financial-field.com/wp-json/
Query: ?page=search-regex.php&searchphrase=style%3D%22color%3A%20%23000000%20%21important%3B%20padding-left%3A%2014px%3B%20border-left%3A%204px%20solid%20%230c5ed4%3B%20font-size%3A%2018px%20%21important%3B%20font-weight%3A%20600%3B%20line-height%3A%201.5%3B%22%20class%3D%22c-sub_heading%20u-article_item_margin%22

Error: Unexpected token < in JSON at position 0 (SyntaxError)
Raw: <html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->

```

**Comment by johngodley** [comment] 2021-01-25 07:55
Your REST API is returning the above message. This is likely caused by some security software

**Comment by johngodley** [comment] 2021-10-03 13:00
Closing for now, please reopen with more information.

**Closed by johngodley** 2021-10-03 13:00 UTC
