### ISSUE TITLE
Search Regex Error

### ISSUE THREAD

**Issue by periwiliam** [johngodley/search-regex#60] opened 2020-09-13 02:36 UTC
```
Plugin: 2.3.2
WordPress: 5.5.1 (single)
PHP: 7.2.30-1+0~20200419.40+debian9~1.gbpb1b799 1024M 6000s
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36
JavaScript: https://book.mangmoba.com/wp-content/plugins/search-regex/search-regex.js
REST API: https://book.mangmoba.com/wp-json/
Query: ?page=search-regex.php&searchphrase=https%3A%2F%2Fbook.mangmoba.com%2Fwp-content
Buster: 2.3.2 === 2.3.2

TypeError: Cannot read property 'http' of undefined

    in ga
    in div
    in div
    in Qa
    in div
    in Ka
    in div
    in i
    in f
    in Zi
    in ba
    in div
    in ja
    in tu
    in div
    in u
    in Unknown
    in f
    in StrictMode
    in Le
    in Oc
```

**Comment by johngodley** [comment] 2020-09-13 07:33
This is an error that is occurs when trying to show an error. It will be fixed in a future release, but you've already reported the root cause, and that is the one to focus on.

**Closed by johngodley** 2020-09-13 07:33 UTC
